---

- name: Deploy local configuration
  template:
    src:   roles/webdevops-mail-sandbox/templates/postfix/recipient_canonical_maps.txt.j2
    dest:  /etc/postfix/recipient_canonical_maps
    owner: root
    group: root
    mode:  0644

- name: Postfix configuration
  lineinfile:
    dest:   /etc/postfix/main.cf
    regexp: '^[\s#]*{{ item.variable }}[\s]*='
    line:   '{{ item.variable }}={{ item.value }}'
  with_items:
    - { variable: 'mynetworks',               value: 'localhost {{ansible_hostname}} 0.0.0.0/0 [::1]/0' }
    - { variable: 'mydestination',            value: 'localhost {{ansible_hostname}}' }
    - { variable: 'recipient_canonical_maps', value: 'regexp:/etc/postfix/recipient_canonical_maps' }

- name: Postmap postfix
  command: '{{ item }}'
  with_items:
    - postmap /etc/postfix/recipient_canonical_maps
