- user:
    name:     "{{ MAILBOX_USERNAME }}"
    password: "{{ MAILBOX_PASSWORD }}"
    comment:  "Mailbox"

- stat:
    path: "/var/mail/{{ MAILBOX_USERNAME }}/"
  register: mailbox

- file:
    path:  "/var/mail/{{ MAILBOX_USERNAME }}/.mail/"
    state: directory
    recurse: yes
    mode:  0755
    owner: "{{ MAILBOX_USERNAME }}"
    group: "{{ MAILBOX_USERNAME }}"
  when: mailbox.stat.exists is not defined or mailbox.stat.exists == False

- name: create maildir subfolders
  command: maildirmake.dovecot .{{ item }}
           chdir=/var/mail/{{ MAILBOX_USERNAME }}/.mail
           creates=/var/mail/{{ MAILBOX_USERNAME }}/.mail/.{{ item }}
  with_items:
    - Archive
    - Drafts
    - Sent
    - Spam
    - Trash
  when: mailbox.stat.exists is not defined or mailbox.stat.exists == False

